- build.gradle
- src/main/java/com/example/rentalSystem/domain/common/BaseTimeEntity.java
- src/main/java/com/example/rentalSystem/domain/facility/convert/StringListConverter.java
- src/main/java/com/example/rentalSystem/domain/facility/entity/Facility.java
- src/main/java/com/example/rentalSystem/domain/professor/entity/Professor.java
- src/main/java/com/example/rentalSystem/domain/rentalhistory/entity/RentalApplicationResult.java
- src/main/java/com/example/rentalSystem/domain/rentalhistory/entity/RentalHistory.java
- src/main/java/com/example/rentalSystem/domain/student/entity/Student.java
- src/main/java/com/example/rentalSystem/global/config/JpaConfig.java
- src/main/java/com/example/rentalSystem/global/config/SwaggerConfig.java
- src/main/java/com/example/rentalSystem/global/exception/GlobalExceptionHandler.java
- src/main/java/com/example/rentalSystem/global/exception/custom/CustomException.java
- src/main/java/com/example/rentalSystem/global/response/ApiResponse.java
- src/main/java/com/example/rentalSystem/global/response/ErrorType.java
- src/main/java/com/example/rentalSystem/global/response/ExceptionResponse.java
- src/main/java/com/example/rentalSystem/global/response/HttpStatusCode.java
- src/main/java/com/example/rentalSystem/global/response/SuccessType.java
- src/main/resources/application.properties
- src/main/resources/application.yml
프로젝트에 필요한 초기 설정, 세팅 하였습니다.
1. Facility 엔터티 부분에서 이미지 여러 개 저장 하는게 맞나요? 값을 여러 개 저장할 때, 컨버터 사용했는데, 엔터티로 따로 빼야 하는지,
2. ERD 부분에서 Facility 엔터티 필드에 구비시설이 뭔가요
close #1
> 프로젝트 초기 세팅

- .github/workflows/deploy.yml
ci/cd 연습용으로 develop으로 push 되었을 때 어떻게 진행되는 지 확인
close #이슈번호
> chore : ci/cd 테스트

- build.gradle
- src/main/java/com/example/rentalSystem/domain/common/BaseTimeEntity.java
- src/main/java/com/example/rentalSystem/domain/facility/convert/StringListConverter.java
- src/main/java/com/example/rentalSystem/domain/facility/entity/Facility.java
- src/main/java/com/example/rentalSystem/domain/professor/entity/Professor.java
- src/main/java/com/example/rentalSystem/domain/rentalhistory/entity/RentalHistory.java
- src/main/java/com/example/rentalSystem/domain/student/entity/Student.java
- src/main/java/com/example/rentalSystem/global/config/JpaConfig.java
- src/main/java/com/example/rentalSystem/global/config/SwaggerConfig.java
- src/main/java/com/example/rentalSystem/global/response/ApiResponse.java
lombok 의존성 문제 + record @getter 제거
close #이슈번호
> chore : lombok 의존성 문제 + record @getter 제거

- .github/workflows/deploy.yml
- build.gradle
- docker-compose.yml
- src/main/resources/application-dev.yml
- src/main/resources/application-local.yml
- src/main/resources/application.yml
> feat : RDS 연동 및 local db 연결

- src/main/java/com/example/rentalSystem/user/UserController.java
> env : CICD 테스트

- src/main/resources/application.yml
docker compose not found 에러
close #이슈번호
> fix : docker compose not found

- build.gradle
- src/main/resources/application.yml
> fix : docker-compose not found

- src/main/java/com/example/rentalSystem/user/UserController.java
> fix : 테스트 api 삭제

- src/main/resources/application-dev.yml
dev.yml안에 validate -> create-drop
개발 단계에선 일단 create-drop을 통해 돌아가게 하는 것이 우선이기에 일단 이렇게 했습니다.
프론트쪽 연결을 위해서 빠르게 베포된 것을 확인해야합니다.
close #이슈번호
> chore : 개발 단계에서 create-drop을 통해 돌아가는 지 확인하도록 변경

- .github/workflows/deploy.yml
도커 이미지를 ecr로 푸쉬하는 워크플로우 작성
- 공개적인 저장소인 Docker Hub가 아닌 aws의 private ecr로 푸쉬하는 기능 구현
close #이슈번호
> ci : ecr에 도커 이미지 푸쉬하는 플로우 작성

- .github/workflows/deploy.yml
> ci : secret라는 네임 스페이스 명시

- .github/workflows/deploy.yml
> ci : gradle 버전 명시 제거, build 안의 값으로 하도록 설정

- src/main/java/com/example/rentalSystem/domain/affiliation/type/AffiliationType.java
- src/main/java/com/example/rentalSystem/domain/member/entity/Member.java
- src/main/java/com/example/rentalSystem/domain/rentalhistory/controller/RentalController.java
- src/main/java/com/example/rentalSystem/domain/rentalhistory/dto/response/RentalHistoryResponseDto.java
- src/main/java/com/example/rentalSystem/domain/rentalhistory/service/RentalService.java
- src/main/java/com/example/rentalSystem/domain/student/dto/request/StudentSignUpRequest.java
- src/main/java/com/example/rentalSystem/domain/student/entity/Student.java
- src/test/java/com/example/rentalSystem/common/fixture/FacilityFixture.java
- src/test/java/com/example/rentalSystem/common/fixture/RentalFixture.java
- src/test/java/com/example/rentalSystem/common/fixture/StudentFixture.java
- src/test/java/com/example/rentalSystem/domain/facility/controller/FacilityControllerTest.java
- src/test/java/com/example/rentalSystem/domain/rentalHistory/controller/RentalControllerTest.java
- src/test/java/com/example/rentalSystem/domain/student/controller/StudentControllerTest.java
1. Student의 college, major의 클래스를 String -> AffiliationType으로 관리하도록 변경
2. test 대여 내역 전체 조회, 시설 전체 조회 페이징 처리 추가
close #이슈번호
> [refactor/test]  Student의 college,major 클래스를 AffiliationType으로 변경 / 대여 내역 전체 조회, 시설 전체 조회 페이징 처리 추가

- src/docs/asciidoc/rental.html
- src/main/java/com/example/rentalSystem/domain/rentalhistory/controller/RentalController.java
- src/main/java/com/example/rentalSystem/domain/rentalhistory/dto/response/RentalHistoryDetailResponseDto.java
- src/main/java/com/example/rentalSystem/domain/rentalhistory/entity/RentalHistory.java
- src/main/java/com/example/rentalSystem/domain/rentalhistory/service/RentalService.java
- src/main/resources/static/docs/email.html
- src/main/resources/static/docs/index.html
- src/main/resources/static/docs/members.html
- src/main/resources/static/docs/rental.html
> [Feat] 대여내역 상세 조회 

- src/main/java/com/example/rentalSystem/domain/affiliation/type/AffiliationType.java
- src/main/java/com/example/rentalSystem/domain/facility/convert/AffiliationListConverter.java
- src/main/java/com/example/rentalSystem/domain/facility/dto/request/CreateFacilityRequestDto.java
- src/main/java/com/example/rentalSystem/domain/facility/dto/response/FacilityDetailResponse.java
- src/main/java/com/example/rentalSystem/domain/facility/dto/response/FacilityResponse.java
- src/main/java/com/example/rentalSystem/domain/facility/entity/Facility.java
- src/main/java/com/example/rentalSystem/domain/facility/service/FacilityService.java
Facility 엔터티가 가지고 있던 allowedBoundary를 제대로 확립했습니다.
AffiliationType enum 클래스안에 getChildList를 통해서 학부안의 존재하는 학과 리스트를 반환하도록 했습니다.
close #이슈번호
> [Feat] : 시설마다 대여할 수 있는 소속을 갖도록 추가

- src/main/java/com/example/rentalSystem/domain/common/PagedResponse.java
- src/main/java/com/example/rentalSystem/domain/facility/controller/FacilityController.java
기존 Page<> 형태의 응답값으론 불필요한 필드도 존재하여 PagedResponse라는 dto를 따로 구현
바뀌기 전
바뀐 후
후에 프론트분과 논의를 통해 필요한 필드값을 더 추가할 계획입니다.
close #이슈번호
> refactor : 기존 Page<> 형태의 응답값으론 불필요한 필드도 존재하여 PagedResponse라는 dto를 따로 구현

- src/main/java/com/example/rentalSystem/domain/pic/entity/Pic.java
- src/main/java/com/example/rentalSystem/domain/professor/controller/ProfessorController.java
> [Feat] : 교직원 엔터티 추가

- src/main/java/com/example/rentalSystem/domain/professor/entity/Professor.java
- src/main/java/com/example/rentalSystem/domain/rentalhistory/entity/RentalHistory.java
- [ dba85cd03621bfd7f2ba24914f76f55d6cd33c11] 대여내역에 pic가 오히려 nullable이 false여서 변경
- [4570511181a326b082f496fbe832848f4b0cfe1d] @GeneratedValue가 있기에 생성자 매개변수에 id 제거
close #이슈번호
> [Refactor] nullable = false 제거, 빌더 패턴 매개변수 id 제거

- src/main/java/com/example/rentalSystem/domain/facility/controller/FacilityControllerDocs.java
- src/main/java/com/example/rentalSystem/domain/facility/controller/dto/request/CreateFacilityRequestDto.java
- src/main/java/com/example/rentalSystem/domain/professor/controller/ProfessorControllerDocs.java
- src/main/java/com/example/rentalSystem/domain/rentalhistory/controller/RentalControllerDocs.java
- src/main/java/com/example/rentalSystem/domain/rentalhistory/controller/dto/request/CreateRentalRequest.java
- src/main/java/com/example/rentalSystem/domain/student/controller/dto/request/StudentSignInRequest.java
- src/main/java/com/example/rentalSystem/domain/student/controller/dto/request/StudentSignUpRequest.java
> [Feat] 스웨거의 요청값 예시를 위한 @Schema, @Parameter 처리 

- src/main/java/com/example/rentalSystem/domain/facility/controller/dto/response/FacilityDetailResponse.java
- src/main/java/com/example/rentalSystem/domain/facility/service/FacilityService.java
> feat : 시설 이미지 Url을 presigned url로 변환하여 전달하기

- src/main/java/com/example/rentalSystem/domain/facility/controller/dto/request/CreateFacilityRequestDto.java
시설을 등록할 때 대여 가능한 시간을 30분 단위로 나누기 때문에 초가 필요 없기 때문에 시간과 분만 직렬화되도록 변경
close #이슈번호
> [Refactor] LocalTime 직렬화 포맷을 HH:mm으로 하도록 변경

- docker-compose.yml
> [Refactor] 도커 컨테이너 시간대 변경

- src/main/java/com/example/rentalSystem/global/auth/jwt/JwtAuthenticationFilter.java
> 클라이언트에서 토큰이 잘 오는 지 확인

- src/main/java/com/example/rentalSystem/domain/facility/controller/dto/request/CreateFacilityRequestDto.java
- src/main/java/com/example/rentalSystem/domain/facility/entity/timeTable/TimeTable.java
- src/main/java/com/example/rentalSystem/global/config/SecurityConfig.java
> SecurityFilter 수정

- build.gradle
- src/main/java/com/example/rentalSystem/domain/facility/service/FacilityService.java
> 프로세서 연습 제거

- src/main/java/com/example/rentalSystem/domain/book/schedule/controller/ScheduleController.java
- src/main/java/com/example/rentalSystem/domain/book/schedule/controller/ScheduleControllerDocs.java
- src/main/java/com/example/rentalSystem/domain/book/schedule/dto/request/ExcelScheduleRow.java
- src/main/java/com/example/rentalSystem/domain/book/schedule/dto/request/ScheduleRequest.java
- src/main/java/com/example/rentalSystem/domain/book/schedule/dto/response/ScheduleImportResponse.java
- src/main/java/com/example/rentalSystem/domain/book/schedule/entity/Schedule.java
- src/main/java/com/example/rentalSystem/domain/book/schedule/implement/ScheduleRemover.java
- src/main/java/com/example/rentalSystem/domain/book/schedule/importer/exception/InvalidScheduleRowException.java
- src/main/java/com/example/rentalSystem/domain/book/schedule/importer/exception/ScheduleImportException.java
- src/main/java/com/example/rentalSystem/domain/book/schedule/importer/mapper/ScheduleRowMapper.java
- src/main/java/com/example/rentalSystem/domain/book/schedule/importer/parser/XlsScheduleParser.java
- src/main/java/com/example/rentalSystem/domain/book/schedule/importer/validator/ScheduleRowValidator.java
- src/main/java/com/example/rentalSystem/domain/book/schedule/repository/ScheduleRepository.java
- src/main/java/com/example/rentalSystem/domain/book/schedule/service/ScheduleImportService.java
- src/main/java/com/example/rentalSystem/domain/facility/implement/FacilityImpl.java
엑셀 업로드 기반 스케줄 관리 기능 개선 및 테스트 데이터 추가
- feat: 엑셀 업로드 시 기존 스케줄과 겹치는 데이터는 업데이트, 새로운 데이터는 삽입되도록 로직 개선
- docs: `ScheduleControllerDocs` 인터페이스에 `/upload-excel` API 명세 보강
- chore: 테스트용 더미 스케줄 엑셀 파일(`schedule_dummy.xlsx`) 생성
- 시간표 더미 데이터 추가 생성 필요
> Class schedule file importer

- src/main/java/com/example/rentalSystem/domain/facility/controller/FacilityController.java
시설 수정 API(UpdateFacility)에서 이미지 관리 기능을 통합적으로 지원하도록 확장했습니다.  
프론트는 기존 엔드포인트를 그대로 사용하면서 이미지 추가/삭제/정렬이 가능하며, presigned URL 발급도 한 번에 처리됩니다.
- UpdateFacilityRequestDto 확장
- `removeKeys`: 삭제할 이미지 S3 키
- `addFileNames`: 새로 추가할 원본 파일명
- `newOrder`: 최종 반영할 이미지 순서
- `hardDelete`: true일 경우 S3에서도 물리 삭제
- FacilityService.update
- remove → add → reorder 순으로 처리
- presigned PUT URL은 추가 요청에 대해서만 반환
- 기존 facilityNumber는 수정 불가
- S3Service 연동하여 실제 객체 삭제/업로드 presigned 처리
- 프론트는 "수정하기" 버튼을 눌러야 최종 반영됨
- 응답의 `presignedUrlList`는 추가 업로드가 필요할 때만 채워짐
- 삭제/정렬은 API 호출 시 서버에서 즉시 반영
- 프론트엔드: 
- 응답 구조는 동일하지만 `imageMetas`가 함께 내려옴
- presigned PUT URL이 비어 있으면 추가 업로드 없음
- 수정 후 상세 GET으로 갱신 필요
> feat: 시설 수정 API 확장 – 이미지 추가/삭제/정렬 및 presigned 업로드 통합
